(ns starcraft.replay.action-maps)

(def *attacks*
     {0x06 "Move by click move icon"
      0x08 "Attack"
      0x09 "Gather"
      0x0E "Attack Move"
      0x13 "Failed Casting"
      0x1B "Infest CC"
      0x22 "Repair"
      0x27 "Clear Rally"
      0x28 "Set Rally"
      0x4F "Gather"
      0x50 "Gather"
      0x70 "Unload"
      0x71 "Yamato"
      0x73 "Lockdown"
      0x77 "Dark Swarm"
      0x78 "Parasite"
      0x79 "Spawn Broodling"
      0x7A "EMP"
      0x7E "Launch Nuke"
      0x84 "Lay Mine"
      0x8B "ComSat Scan"
      0x8D "Defense Matrix"
      0x8E "Psionic Storm"
      0x8F "Recall"
      0x90 "Plague"
      0x91 "Consume"
      0x92 "Ensnare"
      0x93 "Stasis"
      0x94 "Hallucination"
      0x98 "Patrol"
      0xB1 "Heal"
      0xB4 "Restore"
      0xB5 "Disruption Web"
      0xB6 "Mind Control"
      0xB8 "Feedback"
      0xB9 "Optic Flare"
      0xBA "Maelstrom"
      0xC0 "Irradiate"})

(def *units*
     {0x00 "Marine"
      0x01 "Ghost"
      0x02 "Vulture"
      0x03 "Goliath"
      0x05 "Siege Tank"
      0x07 "SCV"
      0x08 "Wraith"
      0x09 "Science Vessel"
      0x0B "Dropship"
      0x0C "Battlecruiser"
      0x0E "Nuke"
      0x20 "Firebat"
      0x22 "Medic"
      0x25 "Zergling"
      0x26 "Hydralisk"
      0x27 "Ultralisk"
      0x29 "Drone"
      0x2A "Overlord"
      0x2B "Mutalisk"
      0x2C "Guardian"
      0x2D "Queen"
      0x2E "Defiler"
      0x2F "Scourge"
      0x32 "Infested Terran"
      0x3A "Valkyrie"
      0x3C "Corsair"
      0x3D "Dark Templar"
      0x3E "Devourer"
      0x40 "Probe"
      0x41 "Zealot"
      0x42 "Dragoon"
      0x43 "High Templar"
      0x45 "Shuttle"
      0x46 "Scout"
      0x47 "Arbiter"
      0x48 "Carrier"
      0x53 "Reaver"
      0x54 "Observer"
      0x67 "Lurker"
      0x6A "Command Center"
      0x6B "ComSat"
      0x6C "Nuclear Silo"
      0x6D "Supply Depot"
      0x6E "Refinery"
      0x6F "Barracks"
      0x70 "Academy"
      0x71 "Factory"
      0x72 "Starport"
      0x73 "Control Tower"
      0x74 "Science Facility"
      0x75 "Covert Ops"
      0x76 "Physics Lab"
      0x78 "Machine Shop"
      0x7A "Engineering Bay"
      0x7B "Armory"
      0x7C "Missile Turret"
      0x7D "Bunker"
      0x82 "Infested CC"
      0x83 "Hatchery"
      0x84 "Lair"
      0x85 "Hive"
      0x86 "Nydus Canal"
      0x87 "Hydralisk Den"
      0x88 "Defiler Mound"
      0x89 "Greater Spire"
      0x8A "Queens Nest"
      0x8B "Evolution Chamber"
      0x8C "Ultralisk Cavern"
      0x8D "Spire"
      0x8E "Spawning Pool"
      0x8F "Creep Colony"
      0x90 "Spore Colony"
      0x92 "Sunken Colony"
      0x95 "Extractor"
      0x9A "Nexus"
      0x9B "Robotics Facility"
      0x9C "Pylon"
      0x9D "Assimilator"
      0x9F "Observatory"
      0xA0 "Gateway"
      0xA2 "Photon Cannon"
      0xA3 "Citadel of Adun"
      0xA4 "Cybernetics Core"
      0xA5 "Templar Archives"
      0xA6 "Forge"
      0xA7 "Stargate"
      0xA9 "Fleet Beacon"
      0xAA "Arbiter Tribunal"
      0xAB "Robotics Support Bay"
      0xAC "Shield Battery"
      0xC0 "Larva"
      0xC1 "Rine/Bat"
      0xC2 "Dark Archon"
      0xC3 "Archon"
      0xC4 "Scarab"
      0xC5 "Interceptor"
      0xC6 "Interceptor/Scarab"})


(def *researches*
     {
      0x00 "Stim Pack"
      0x01 "Lockdown"
      0x02 "EMP Shockwave"
      0x03 "Spider Mines"
      0x05 "Siege Tank"
      0x07 "Irradiate"
      0x08 "Yamato Gun"
      0x09 "Cloaking Field (Wraith)"
      0x0A "Personal Cloaking (Ghost)"
      0x0B "Burrow"
      0x0D "Spawn Broodling"
      0x0F "Plague"
      0x10 "Consume"
      0x11 "Ensnare"
      0x13 "Psionic Storm"
      0x14 "Hallucination"
      0x15 "Recall"
      0x16 "Stasis Field"
      0x18 "Restoration"
      0x19 "Disruption Web"
      0x1B "Mind Control"
      0x1E "Optical Flare"
      0x1F "Maelstrom"
      0x20 "Lurker Aspect"})

(def *upgrades*
     {0x00 "Terran Infantry Armor"
      0x01 "Terran Vehicle Plating"
      0x02 "Terran Ship Plating"
      0x03 "Zerg Carapace"
      0x04 "Zerg Flyer Carapace"
      0x05 "Protoss Ground Armor"
      0x06 "Protoss Air Armor"
      0x07 "Terran Infantry Weapons"
      0x08 "Terran Vehicle Weapons"
      0x09 "Terran Ship Weapons"
      0x0A "Zerg Melee Attacks"
      0x0B "Zerg Missile Attacks"
      0x0C "Zerg Flyer Attacks"
      0x0D "Protoss Ground Weapons"
      0x0E "Protoss Air Weapons"
      0x0F "Protoss Plasma Shields"
      0x10 "U-238 Shells (Marine Range)"
      0x11 "Ion Thrusters (Vulture Speed)"
      0x13 "Titan Reactor (Science Vessel Energy)"
      0x14 "Ocular Implants (Ghost Sight)"
      0x15 "Moebius Reactor (Ghost Energy)"
      0x16 "Apollo Reactor (Wraith Energy)"
      0x17 "Colossus Reactor (Battle Cruiser Energy)"
      0x18 "Ventral Sacs (Overlord Transport)"
      0x19 "Antennae (Overlord Sight)"
      0x1A "Pneumatized Carapace (Overlord Speed)"
      0x1B "Metabolic Boost (Zergling Speed)"
      0x1C "Adrenal Glands (Zergling Attack)"
      0x1D "Muscular Augments (Hydralisk Speed)"
      0x1E "Grooved Spines (Hydralisk Range)"
      0x1F "Gamete Meiosis (Queen Energy)"
      0x20 "Defiler Energy"
      0x21 "Singularity Charge (Dragoon Range)"
      0x22 "Leg Enhancement (Zealot Speed)"
      0x23 "Scarab Damage"
      0x24 "Reaver Capacity"
      0x25 "Gravitic Drive (Shuttle Speed)"
      0x26 "Sensor Array (Observer Sight)"
      0x27 "Gravitic Booster (Observer Speed)"
      0x28 "Khaydarin Amulet (Templar Energy)"
      0x29 "Apial Sensors (Scout Sight)"
      0x2A "Gravitic Thrusters (Scout Speed)"
      0x2B "Carrier Capacity"
      0x2C "Khaydarin Core (Arbiter Energy)"
      0x2F "Argus Jewel (Corsair Energy)"
      0x31 "Argus Talisman (Dark Archon Energy)"
      0x33 "Caduceus Reactor (Medic Energy)"
      0x34 "Chitinous Plating (Ultralisk Armor)"
      0x35 "Anabolic Synthesis (Ultralisk Speed)"
      0x36 "Charon Boosters (Goliath Range)"})
      
